# Site settings

title: Project Pages
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/project-pages"
url: "http://matin-hub.github.io"
github_username:  matin-hub
project_repository: project-pages
disqus_shortname: project-pages

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
